config/routes.rb
Rails.application.routes.draw do
  root "homes#index"
  devise_for :users, controllers: { invitations: "users/invitations" }

  resources :organizations, except: [:destroy] do
    resources :items, except: [:show]
  end

  resources :items do
    collection do
      get "search"
    end
  end

  resources :items, only: [:show] do
    resources :dibs, only: [:new, :create, :update, :destroy]
  end

  resources :thumbnails, only: [:new]

  resources :dibs, only: [:index]

  resources :imports, only: [:new, :create, :show]
end

app/models/dib.rb
class Dib < ActiveRecord::Base
  belongs_to :user
  belongs_to :item

  validates :user, presence: true
  validates :item, presence: true
  validates :quantity, presence: true

  def self.incoming_dibs_list(items)
    all_dibs = []
    items.each do |item|
      unless item.dibs.nil?
        item.dibs.each do |dib|
          unless dib.status == "Received"
            dib_info = {}
            dib_info[:name] = item.name
            dib_info[:quantity] = dib.quantity
            dib_info[:volunteer] = User.find(dib.user_id).first_name
            dib_info[:date] = dib.created_at.strftime("%B %d, %Y")
            dib_info[:item_id] = item.id
            dib_info[:dib_id] = dib.id
            dib_info[:organization_id] = item.organization.id
            all_dibs << dib_info
          end
        end
      end
    end
    all_dibs
  end
end

app/controllers/dibs_controller.rb
class DibsController < ApplicationController
  before_action :authenticate_user!

  def new
    @dib = Dib.new
    @item = params[:item]
  end

  def create
    @item = Item.find(params[:item_id])
    @organization = @item.organization
    @dib = Dib.new(dib_params) do |dib|
      dib.user = current_user
      dib.item = @item
    end

    if @dib.quantity == nil
      flash[:error] = "Please specify a quantity."
      render "organizations/show"
    elsif @dib.quantity > @item.quantity
      flash[:notice] = %{Please specify an amount less than or
                         equal to the total needed.}
      render "organizations/show"
    else @dib.save
      @item.update(quantity: @item.quantity - @dib.quantity)
      flash[:notice] = %{Thanks so much! You can see all your promised items
                         and delivery instructions in \"My Items\" above.}
      redirect_to organization_path(id: @organization.id)
    end
  end

  def update
    @dib = Dib.find(params[:id])
    @item = Item.find(params[:item_id])
    @organization = @item.organization
    if @dib.update(dib_params)
      flash[:notice] = "This item has been marked as received,
                         and the provider has been notified."
      redirect_to organization_items_path(@organization, @item)
    else
      flash[:error] = "This item could not be updated."
    end
  end

  def index
    @dibs = Dib.where(user_id: current_user)
  end

  def destroy
    @dib = Dib.find(params[:id])
    @item = Item.find(params[:item_id])
    @dib.destroy
    organization = @item.organization
    new_total_needed = @item.quantity + @dib.quantity
    @item.update(quantity: new_total_needed)
    flash[:notice] = "This item has been removed from your list and returned
                      to #{organization.name}'s wishlist."
    redirect_to dibs_path
  end

  protected

  def dib_params
    params.require(:dib).permit(:quantity, :status)
  end
end

app/views/dibs/_form.html.erb
<%= form_for [item, dib] do |f| %>
  <%= f.label :quantity %>
  <%= f.number_field :quantity %>

  <%= f.submit "I'll get this!", class: "button small success" %>
<% end %>

app/views/dibs/index.html.erb
<div class="small-12 my-items-header">
  <h1 class="text-center">My Items</h1>
</div>
<div class="small-12 medium-8 medium-offset-2 margins columns">
  <ul>
  <% @dibs.each do |dib| %>
    <li><%= dib.quantity %> <%= dib.item.name %> for <%= link_to dib.item.organization.name, organization_path(dib.item.organization.id) %>.<br/>
    <% if dib.status == "Received" %>
      <p class="success">This item has been received. Thank you!</p>
    <% else %>
      Address: <%= dib.item.organization.address %><br/>
      <%= dib.item.organization.city %>, <%= dib.item.organization.state %> <%= dib.item.organization.zip %><br/>
      Delivery instructions: <%= dib.item.organization.delivery_instructions %><br/>
      <%= button_to "I can no longer provide this item.", item_dib_path(item_id: dib.item.id, id:dib.id), method: :delete, class: "button alert small" %></li>

    </li>
    <% end %>
  <% end %>
  </ul>
</div>