config/routes.rb
Rails.application.routes.draw do
  root "homes#index"
  devise_for :users, controllers: { invitations: "users/invitations" }

  resources :organizations, except: [:destroy] do
    resources :items, except: [:show]
  end

  resources :items do
    collection do
      get "search"
    end
  end

  resources :items, only: [:show] do
    resources :dibs, only: [:new, :create, :update, :destroy]
  end

  resources :thumbnails, only: [:new]

  resources :dibs, only: [:index]

  resources :imports, only: [:new, :create, :show]
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    render layout: 'homepage_layout'
  end
end

app/views/homes/index.html.erb
<div class="homepage-container">
<%- flash.each do |key, value| -%>
<div data-alert class="alert-box">
  <div class="flash flash-<%= key %>">
    <%= value %>
  </div>
  <a href="#" class="close">&times;</a>
  </div>
<%- end -%>

  <div class="headline-box">
    <h1 class="text-center animated fadeInDownBig">Share Necessities connects volunteers to the material needs of humanitarian non-profits via wishlists.</h1>
    </div>

  <div class="row">
    <div class="small-12 columns">
      <h2 class="text-center i-am">I am...</h2>
    </div>
    <div class="small-6 columns">
      <h2><%= link_to "a volunteer, and <br/> I want to help.".html_safe, organizations_path %></h2>
    </div>
    <div class="small-6 columns">
    <h2><%= link_to "an organizer, and <br/> I want to add my organization.".html_safe, new_organization_path %></h2>
    </div>
  </div>
</div>