config/routes.rb
Rails.application.routes.draw do
  root "homes#index"
  devise_for :users, controllers: { invitations: "users/invitations" }

  resources :organizations, except: [:destroy] do
    resources :items, except: [:show]
  end

  resources :items do
    collection do
      get "search"
    end
  end

  resources :items, only: [:show] do
    resources :dibs, only: [:new, :create, :update, :destroy]
  end

  resources :thumbnails, only: [:new]

  resources :dibs, only: [:index]

  resources :imports, only: [:new, :create, :show]
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="small-12 columns footer">
    <p class="text-center top-margin">This breakable toy brought to you by <%= link_to "MLG", "http://www.melissaleighgore.com" %>.</p>
    <p class="text-center"><%= link_to "<i class=\"fa fa-github fa-2x\"></i>".html_safe, "http://www.github.com/mlg-" %>&nbsp;&nbsp;<%= link_to "<i class=\"fa fa-linkedin fa-2x\"></i>".html_safe, "http://www.linkedin.com/in/melissaleighgore" %></p>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><a href="/">SHARE NECESSITIES <i class="fa fa-coffee fa-lg"></i></a></h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#"><span></span></a></li>
  </ul>

  <section class="top-bar-section">
    <ul class="right">
      <%- if current_user -%>
        <% if User.organizer?(current_user) %>
          <li class="has-dropdown">
          <a href="#">My Organizations</a>
            <ul class="dropdown">
              <% Organizer.where(user_id: current_user.id).each do |org| %>
                <li><%= link_to org.organization.name, organization_path(id: org.organization.id) %></li>
              <% end %>
            </ul>
          </li>
        <% end %>
        <% if !current_user.dibs.empty? %>
          <li><%= link_to "My Items (#{current_user.dibs.where(status: "Promised").count})", dibs_path %></li>
         <% end %>
        <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
      <%- else -%>
        <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <li><%= link_to 'Sign In', new_user_session_path %></li>
      <%- end -%>
    </ul>
  </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShareNecessities</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= stylesheet_link_tag 'application', "http://fonts.googleapis.com/css?family=Quattrocento+Sans" %>
  <%= stylesheet_link_tag 'application', "http://fonts.googleapis.com/css?family=Oswald:300,400" %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= favicon_link_tag image_path("favicon.ico") %>
</head>
<body>
  
  <%= render "layouts/header" %>

    <%- flash.each do |key, value| -%>
    <div data-alert class="alert-box">
      <div class="flash flash-<%= key %>">
        <%= value %>
      </div>
      <a href="#" class="close">&times;</a>
      </div>
    <%- end -%>

      <%= yield %>

      <%= render "layouts/footer" %>

  <%= javascript_include_tag 'application' %>
  <%= yield :extra_footer %>
</body>
</html>

app/views/layouts/homepage_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShareNecessities</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= stylesheet_link_tag 'application', "http://fonts.googleapis.com/css?family=Quattrocento+Sans" %>
  <%= stylesheet_link_tag 'application', "http://fonts.googleapis.com/css?family=Oswald:300,400" %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= favicon_link_tag image_path("favicon.ico") %>
</head>
<body>
  
  <%= render "layouts/header" %>

  <%= yield %>

  <%= render "layouts/footer" %>

  <%= javascript_include_tag 'application' %>
  <%= yield :extra_footer %>
</body>
</html>